=== airatchaplin/filedossier/filedossier-model/src/main/resources/schemas/filedossier/model.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns="urn:ru:ilb:filedossier:model"
    attributeFormDefault="unqualified"
    elementFormDefault="qualified"
    targetNamespace="urn:ru:ilb:filedossier:model"
>

    <xsd:element name="dossierModel" type="dossierModel"/>
    <xsd:complexType name="dossierModel">
        <xsd:annotation>
            <xsd:documentation>Модель досье</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="code" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>код досье</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="name" type="xsd:string" >
                <xsd:annotation>
                    <xsd:documentation>Наименование досье</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element ref="dossierModelFile" minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                    <xsd:documentation>Файлы досье</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="dossierModelFile" type="dossierModelFile"/>
    <xsd:complexType name="dossierModelFile">
        <xsd:annotation>
            <xsd:documentation>Модель файла досье</xsd:documentation>
        </xsd:annotation>

        <xsd:sequence>
            <xsd:element name="code" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Код файла</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="name" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Наименование</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="readonly" type="xsd:string"  minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation>Только для чтения</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="required" type="xsd:string"  minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation>Обязательный файл</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="visible" type="xsd:string"  minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation>Видимый файл</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
 
</xsd:schema>

=== airatchaplin/filedossier/filedossier-lib/src/test/resources/models/model.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright 2019 slavb.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->


<dossierModel
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="urn:ru:ilb:filedossier:model"
    xsi:schemaLocation="urn:ru:ilb:filedossier:model ../../../../../filedossier-api/src/main/resources/schemas/filedossier/model.xsd">
    <code>TEST</code>
    <name>Тестовое досье</name>
    <dossierModelFile>
        <code>file1</code>
        <name>Файл 1</name>
        <readonly>false</readonly>
        <required>true</required>
    </dossierModelFile>
    <dossierModelFile>
        <code>file2</code>
        <name>Файл 2</name>
        <readonlyExpression>a=false</readonlyExpression>
    </dossierModelFile>

</dossierModel>
